import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ToDoComponents from './components/ToDoComponents';

const Home: NextPage = () => {
  return (
    <div style={{
      background: "linear-gradient(0.125turn, #e66465, #9198e5)", 
      height: "100vh",
      display: "flex",
      justifyContent: "center"
      }}>
    
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToDoComponents/>
      
    </div>
  )
}

export default Home;

